import Head from 'next/head'
import Image from 'next/image'
import { getPosts, homeData } from '../services/pages';
import styles from '../styles/Home.module.css'

export default function Home({ name, description, posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to {name}
        </h1>

        <p className={styles.description}>
          {description}
        </p>

        {posts.map((post) =>
          <div key={post.id}>
            <p>{post.title.rendered}</p>
            <p dangerouslySetInnerHTML={{ __html: post.excerpt.rendered }}/>
          </div>
        )}



      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const { name, description } = await homeData();
  const posts = await getPosts();
  return {
    props: { name, description, posts }, // will be passed to the page component as props
  }
}
